// <auto-generated />
using System;
using ChangeX.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeX.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChangeX.DAL.Entities.CR", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedManHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("FinishDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ManHourRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.HasIndex("CurrentStatusID");

                    b.HasIndex("ProjectID");

                    b.ToTable("CRs", (string)null);
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.CRStatus", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvailableStatusIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CRStatues", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("3f2a9e7d-8b41-4c6a-9d2e-1a7f5c8b3e90"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "2E7C9A4D-5F3B-4C1E-8D6A-7B9F2C4E1A85,8A3E6C1F-4B9D-4E2A-9F7C-2D5B8E4A1C96,7C1D4E2F-9A6B-4F3D-8E7C-2B9A5D1F6C43",
                            CurrentStatus = "Pending Vendor FeedBack"
                        },
                        new
                        {
                            ID = new Guid("7c1d4e2f-9a6b-4f3d-8e7c-2b9a5d1f6c43"),
                            AccessedBy = "Client",
                            AvailableStatusIDs = "3F2A9E7D-8B41-4C6A-9D2E-1A7F5C8B3E90",
                            CurrentStatus = "Pending Client Clarification"
                        },
                        new
                        {
                            ID = new Guid("2e7c9a4d-5f3b-4c1e-8d6a-7b9f2c4e1a85"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "6F4B2E8D-1A9C-4D7F-B3E6-8C2A5F9D4B17",
                            CurrentStatus = "Accepted (CR)"
                        },
                        new
                        {
                            ID = new Guid("6f4b2e8d-1a9c-4d7f-b3e6-8c2a5f9d4b17"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "3F2A9E7D-8B41-4C6A-9D2E-1A7F5C8B3E90",
                            CurrentStatus = "Estimation Created"
                        },
                        new
                        {
                            ID = new Guid("a5e9c3b7-2d4f-4a8e-9c1b-6f3d7e2a9b58"),
                            AccessedBy = "Client",
                            AvailableStatusIDs = "9D3F6A2E-4C8B-4F1D-A7E9-2B6C4D8A3F71,8A3E6C1F-4B9D-4E2A-9F7C-2D5B8E4A1C96",
                            CurrentStatus = "Pending Client Approval"
                        },
                        new
                        {
                            ID = new Guid("9d3f6a2e-4c8b-4f1d-a7e9-2b6c4d8a3f71"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "1C8E4B7A-3D9F-4E2C-B6A8-5F3D9E1C7A42",
                            CurrentStatus = "Accepted (Estimation)"
                        },
                        new
                        {
                            ID = new Guid("1c8e4b7a-3d9f-4e2c-b6a8-5f3d9e1c7a42"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "6A4D2F9E-8C3B-4A7D-9E1F-4B8A6D2C5F93,A5E9C3B7-2D4F-4A8E-9C1B-6F3D7E2A9B58",
                            CurrentStatus = "Analysis"
                        },
                        new
                        {
                            ID = new Guid("6a4d2f9e-8c3b-4a7d-9e1f-4b8a6d2c5f93"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "F3B9E2D4-7A6C-4D8E-B2F1-9C5A3E7D4B26",
                            CurrentStatus = "Design"
                        },
                        new
                        {
                            ID = new Guid("f3b9e2d4-7a6c-4d8e-b2f1-9c5a3e7d4b26"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "E2B7A4C9-6F1D-4E3A-8B9C-3D5A7F2E1C64",
                            CurrentStatus = "Development"
                        },
                        new
                        {
                            ID = new Guid("e2b7a4c9-6f1d-4e3a-8b9c-3d5a7f2e1c64"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "8D4F2C6E-3A9B-4E7D-9C1F-5A2D9B6C3E47",
                            CurrentStatus = "Testing"
                        },
                        new
                        {
                            ID = new Guid("8d4f2c6e-3a9b-4e7d-9c1f-5a2d9b6c3e47"),
                            AccessedBy = "Client",
                            AvailableStatusIDs = "B7E3A9C4-2F8D-4B6E-9A1C-6D4F2E8A7C53,8A3E6C1F-4B9D-4E2A-9F7C-2D5B8E4A1C96,4B9E7C2A-6D3F-4A8E-9C2B-1E7A4D8C6F39",
                            CurrentStatus = "Pending Customer Approval"
                        },
                        new
                        {
                            ID = new Guid("4b9e7c2a-6d3f-4a8e-9c2b-1e7a4d8c6f39"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "1C8E4B7A-3D9F-4E2C-B6A8-5F3D9E1C7A42",
                            CurrentStatus = "Rework Required"
                        },
                        new
                        {
                            ID = new Guid("b7e3a9c4-2f8d-4b6e-9a1c-6d4f2e8a7c53"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "D9A4C2F7-6E3B-4D8A-B7C1-2F9E5A3D8C64",
                            CurrentStatus = "Accepted (Test)"
                        },
                        new
                        {
                            ID = new Guid("d9a4c2f7-6e3b-4d8a-b7c1-2f9e5a3d8c64"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "5C2E8A4D-9F7B-4E1C-A3D6-8B4F2C9E7A15",
                            CurrentStatus = "Deployed"
                        },
                        new
                        {
                            ID = new Guid("5c2e8a4d-9f7b-4e1c-a3d6-8b4f2c9e7a15"),
                            AccessedBy = "Admin",
                            AvailableStatusIDs = "C1F7A4E9-8B2D-4E6C-A3F1-7C9E2A5D8B64",
                            CurrentStatus = "Delivered"
                        },
                        new
                        {
                            ID = new Guid("8a3e6c1f-4b9d-4e2a-9f7c-2d5b8e4a1c96"),
                            AccessedBy = "Admin",
                            CurrentStatus = "Rejected"
                        },
                        new
                        {
                            ID = new Guid("c1f7a4e9-8b2d-4e6c-a3f1-7c9e2a5d8b64"),
                            AccessedBy = "Admin",
                            CurrentStatus = "Completed"
                        });
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.Client", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DefaultContactID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DefaultContactID");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.Detail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CRID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CRID");

                    b.ToTable("Details", (string)null);
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.Invoice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CRID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CRID");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.Project", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SystemRole")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.CR", b =>
                {
                    b.HasOne("ChangeX.DAL.Entities.CRStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChangeX.DAL.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentStatus");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.Client", b =>
                {
                    b.HasOne("ChangeX.DAL.Entities.User", "DefaultContact")
                        .WithMany()
                        .HasForeignKey("DefaultContactID");

                    b.Navigation("DefaultContact");
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.Detail", b =>
                {
                    b.HasOne("ChangeX.DAL.Entities.CR", "CR")
                        .WithMany()
                        .HasForeignKey("CRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CR");
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.Invoice", b =>
                {
                    b.HasOne("ChangeX.DAL.Entities.CR", "CR")
                        .WithMany()
                        .HasForeignKey("CRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CR");
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.Project", b =>
                {
                    b.HasOne("ChangeX.DAL.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ChangeX.DAL.Entities.User", b =>
                {
                    b.HasOne("ChangeX.DAL.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
